# -*- coding: utf-8 -*-
"""Movie Ticket Booking System:

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUarXO78ALMLjn3w8sKF8dSUaGfTpFu5

PYTHON PROJECT FOR MOVIE TICKET BOOKING SYSTEM
"""

import random
class MovieTicketBookingSystem:

    def __init__(self):
        self.movies = []
        self.seats = []

    def add_movie(self, movie_name, screening_time):
        self.movies.append((movie_name, screening_time))

    def add_seats(self, number_of_seats):
        for i in range(number_of_seats):
            self.seats.append(1)

    def book_tickets(self, movie_name, screening_time, number_of_tickets):
        for movie, screening in self.movies:
            if movie == movie_name and screening == screening_time:
                for i in range(number_of_tickets):
                    if self.seats[i] == 1:
                        self.seats[i] = 0
                        break

    def generate_tickets(self):
        tickets = []
        for i, seat in enumerate(self.seats):
            if seat == 0:
                tickets.append((i, movie_name, screening_time))
        return tickets


if __name__ == "__main__":
    movie_ticket_booking_system = MovieTicketBookingSystem()
    movie_ticket_booking_system.add_movie("The Batman", "10:00 AM")
    movie_ticket_booking_system.add_movie("The Lost City", "12:00 PM")
    movie_ticket_booking_system.add_seats(100)
    movie_ticket_booking_system.book_tickets("The Batman", "10:00 AM", 2)
    tickets = movie_ticket_booking_system.generate_tickets()
    for ticket in tickets:
        print(ticket)

"""This program will create a movie ticket booking system with two movies, "The Batman" and "The Lost City". The system will have 100 seats, and users can book up to 2 tickets per screening. The program will then generate printable tickets for the booked seats.

To run this program, you can save it as a `.py` file and then run it from the command line. For example, if you saved the program as `movie_ticket_booking_system.py`, you would run it by typing the following command into the command line:

```
python movie_ticket_booking_system.py
```

This will run the program and print out the generated tickets.
"""